In [2]:
import pandas as pd
import numpy as np
import csv

In [3]:
rounds2 = pd.read_csv("rounds2.csv",encoding="ISO-8859-1")

In [4]:
companies= pd.read_csv("company.csv",encoding="ISO-8859-1")

In [11]:
companies.head()

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/Organization/-Fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
1,/Organization/-Qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
2,/Organization/-The-One-Of-Them-Inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
3,/Organization/0-6-Com,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
4,/Organization/004-Technologies,004 Technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign,01-01-2010

In [13]:
rounds2.head()

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0
1,/ORGANIZATION/-QOUNTER,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN
2,/organization/-qounter,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,01-03-2014,700000.0
3,/ORGANIZATION/-THE-ONE-OF-THEM-INC-,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0
4,/organization/0-6-com,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0

In [ ]:
a = len(rounds2['company_permalink'].unique().tolist())

In [29]:
a

90247

In [17]:
b = len(companies['permalink'].unique().tolist())

In [18]:
b

66368

In [30]:
rounds2.head()

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0
1,/ORGANIZATION/-QOUNTER,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN
2,/organization/-qounter,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,01-03-2014,700000.0
3,/ORGANIZATION/-THE-ONE-OF-THEM-INC-,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0
4,/organization/0-6-com,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0

In [8]:
rounds2.rename(columns={'company_permalink':'permalink'},inplace=True)

In [11]:
rounds2['permalink']=rounds2['permalink'].str.lower()

In [12]:
companies['permalink']=companies['permalink'].str.lower()

In [13]:
rounds2.head()

,permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0
1,/organization/-qounter,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN
2,/organization/-qounter,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,01-03-2014,700000.0
3,/organization/-the-one-of-them-inc-,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0
4,/organization/0-6-com,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0

In [14]:
companies.head()

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/organization/-fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
1,/organization/-qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
2,/organization/-the-one-of-them-inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
3,/organization/0-6-com,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
4,/organization/004-technologies,004 Technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign,01-01-2010

In [20]:
master_frame=rounds2.join ( companies.set_index( [ 'permalink' ], verify_integrity=True ),
               on=[ 'permalink' ], how='inner' )

In [21]:
len(master_frame)

114942

In [22]:
master_frame

,permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
1,/organization/-qounter,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
2,/organization/-qounter,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,01-03-2014,700000.0,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
3,/organization/-the-one-of-them-inc-,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
4,/organization/0-6-com,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
5,/organization/004-technologies,/funding-round/1278dd4e6a37fa4b7d7e06c21b3c1830,venture,NaN,24-07-2014,NaN,004 Technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign,01-01-2010
6,/organization/01games-technology,/funding-round/7d53696f2b4f607a2f2a8cbb83d01839,undisclosed,NaN,01-07-2014,41250.0,01Games Technology,http://www.01games.hk/,Games,operating,HKG,NaN,Hong Kong,Hong Kong,NaN
7,/organization/0ndine-biomedical-inc,/funding-round/2b9d3ac293d5cdccbecff5c8cb0f327d,seed,NaN,11-09-2009,43360.0,Ondine Biomedical Inc.,http://ondinebio.com,Biotechnology,operating,CAN,BC,Vancouver,Vancouver,01-01-1997
8,/organization/0ndine-biomedical-inc,/funding-round/954b9499724b946ad8c396a57a5f3b72,venture,NaN,21-12-2009,719491.0,Ondine Biomedical Inc.,http://ondinebio.com,Biotechnology,operating,CAN,BC,Vancouver,Vancouver,01-01-1997
9,/organization/0xdata,/funding-round/383a9bd2c04f7038bb543ccef5ba3eae,seed,NaN,22-05-2013,3000000.0,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011
10,/organization/0xdata,/funding-round/3bb2ee4a2d89251a10aaa735b1180e44,venture,B,09-11-2015,20000000.0,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011
11,/organization/0xdata,/funding-round/ae2a174c06517c2394aed45006322a7e,venture,NaN,03-01-2013,1700000.0,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011
12,/organization/0xdata,/funding-round/e1cfcbe1bdf4c70277c5f29a3482f24e,venture,A,19-07-2014,8900000.0,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011
13,/organization/1,/funding-round/03b975068632eba5bfdb937ec8c07a68,seed,NaN,05-02-2014,150000.0,One Inc.,http://whatis1.com,Mobile,operating,USA,CA,SF Bay Area,San Francisco,01-08-2011
14,/organization/1,/funding-round/5de6d8828aef7d925d97918d15727670,undisclosed,NaN,05-02-2013,NaN,One Inc.,http://whatis1.com,Mobile,operating,USA,CA,SF Bay Area,San Francisco,01-08-2011
15,/organization/1,/funding-round/e82464f22241715dd1a6c77241055ed1,seed,NaN,20-07-2011,1000050.0,One Inc.,http://whatis1.com,Mobile,operating,USA,CA,SF Bay Area,San Francisco,01-08-2011
16,/organization/1-2-3-listo,/funding-round/6de4609e894495105bc791ed64361288,seed,NaN,18-02-2013,40000.0,"1,2,3 Listo",http://www.123listo.com,E-Commerce,operating,CHL,12,Santiago,Las Condes,01-01-2012
17,/organization/1-4-all,/funding-round/e97a192e13ea0ee3c4f71136b4f3ec16,equity_crowdfunding,NaN,21-04-2013,NaN,1-4 All,NaN,Entertainment|Games|Software,operating,USA,NC,NC - Other,Connellys Springs,NaN
18,/organization/1-618-technology,/funding-round/83b8f4c7d37ecef5e001a5e953bf461a,equity_crowdfunding,NaN,22-01-2014,NaN,1.618 Technology,http://www.Homeandcondogallery.com,Networking|Real Estate|Web Hosting,operating,USA,FL,Orlando,Orlando,07-12-2013
19,/organization/1-800-dentist,/funding-round/5274aacc211163fc7c86539ce94bbacc,undisclosed,NaN,19-08-2010,NaN,1-800-DENTIST,http://www.1800dentist.com,Health and Wellness,operating,USA,CA,Los Angeles,Los Angeles,01-01-1986
20,/organization/1-800-doctors,/funding-round/9eb8c7790a0c200d79e75785d1c4aa12,convertible_note,NaN,02-03-2011,1750000.0,1-800-DOCTORS,http://1800doctors.com,Health and Wellness,operating,USA,NJ,Newark,Iselin,01-01-1984
21,/organization/1-800-publicrelations-inc-,/funding-round/11c228f58831bc7ed337ef69ecc560c2,private_equity,NaN,01-02-2015,6000000.0,"1-800-PublicRelations, Inc.",http://www.1800publicrelations.com,Internet Marketing|Media|Public Relations,operating,USA,NY,New York City,New York,24-10-2013
22,/organization/1-mainstream,/funding-round/b952cbaf401f310927430c97b68162ea,venture,NaN,17-03-2015,5000000.0,1 Mainstream,http://www.1mainstream.com,Apps|Cable|Distribution|Software,acquired,USA,CA,SF Bay Area,Cupertino,01-03-2012
23,/organization/1-of-99,/funding-round/b5c811f561cfb5701cd5b1762120bbc3,convertible_note,NaN,13-12-2014,100000.0,1 of 99,NaN,Entertainment|Games,operating,USA,CA,SF Bay Area,Mountain View,01-12-2014
24,/organization/10-20-media,/funding-round/436874dc54b54460f99f44c06e50990a,debt_financing,NaN,11-01-2011,800000.0,10-20 Media,http://www.10-20media.com,E-Commerce,operating,USA,MD,Baltimore,Woodbine,01-01-2001
25,/organization/10-20-media,/funding-round/8025ee9c11a586eac4a234ddec7beb30,debt_financing,NaN,18-06-2009,500000.0,10-20 Media,http://www.10-20media.com,E-Commerce,operating,USA,MD,Baltimore,Woodbine,01-01-2001
26,/organization/10-20-media,/funding-round/a884bf8326b9fd59789c0f74a28dbc3b,debt_financing,NaN,28-12-2011,500000.0,10-20 Media,http://www.10-20media.com,E-Commerce,operating,USA,MD,Baltimore,Woodbine,01-01-2001
27,/organization/10-20-media,/funding-round/d205f5416ce55e126beda3ed2bf2c2cd,debt_financing,NaN,30-03-2010,250000.0,10-20 Media,http://www.10-20media.com,E-Commerce,operating,USA,MD,Baltimore,Woodbine,01-01-2001
28,/organization/10-minutes-with,/funding-round/0faccbbcc5818dc5326469f13f5a8ac8,venture,A,09-10-2014,4000000.0,10 Minutes With,http://10minuteswith.com,Education,operating,GBR,H9,London,London,01-01-2013
29,/organization/10-minutes-with,/funding-round/f245a74b4c54610ae843e17bdf4d1113,seed,NaN,01-01-2013,400000.0,10 Minutes With,http://10minuteswith.com,Education,operating,GBR,H9,London,London,01-01-2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114919,/organization/zynstra,/funding-round/dee233b3434185c14b3352034f72d798,angel,NaN,18-09-2012,2325000.0,Zynstra,http://www.zynstra.com,Software,operating,GBR,A4,Bath,Bath,30-11-2011
114920,/organization/zyomyx-inc,/funding-round/4191cb5258d3863b0212d1083881da64,venture,B,30-06-2013,12000000.0,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998
114921,/organization/zyomyx-inc,/funding-round/85443f5438bfd50104b9591eabc95c94,grant,NaN,26-03-2014,7500000.0,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998
114922,/organization/zyomyx-inc,/funding-round/b4fce7f8a13267353d57db09099800e8,venture,NaN,11-07-2013,14219999.0,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998
114923,/organization/zyomyx-inc,/funding-round/ea5b21da6cf999ff4d5667431fe318d7,venture,NaN,29-01-2010,555016.0,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998
114924,/organization/zype,/funding-round/24e8134882bf6c4dcc385abba0acd5d9,seed,NaN,01-04-2015,1700000.0,Zype,http://www.zype.com,Cloud Computing|Mobile Advertising|Video|Video...,operating,USA,NY,New York City,New York,01-01-2013
114925,/organization/zype,/funding-round/c9f5097b3617c7539aa47c8b448163be,seed,NaN,27-10-2015,1600000.0,Zype,http://www.zype.com,Cloud Computing|Mobile Advertising|Video|Video...,operating,USA,NY,New York City,New York,01-01-2013
114926,/organization/zypsee,/funding-round/472c6f7940522552fcca465b8cd3deef,seed,NaN,25-09-2013,2150000.0,Whisk (formerly Zypsee),http://whisk.me,Public Transportation,operating,USA,NY,New York City,New York,01-01-2011
114927,/organization/zypsee,/funding-round/c67e22c5448435adaf5a2d101e449dde,seed,NaN,26-07-2013,NaN,Whisk (formerly Zypsee),http://whisk.me,Public Transportation,operating,USA,NY,New York City,New York,01-01-2011
114928,/organization/zyraz-technology,/funding-round/3c3ae0f177e01a04deea811e1828be35,private_equity,NaN,15-02-2013,20967.0,Zyraz Technology,http://www.zyraz.com,Biotechnology,closed,MYS,14,MYS - Other,Damansara New Village,01-01-1994
114929,/organization/zyraz-technology,/funding-round/55f33b179dd6f4516315348c1e8350c6,angel,NaN,01-01-2008,2007363.0,Zyraz Technology,http://www.zyraz.com,Biotechnology,closed,MYS,14,MYS - Other,Damansara New Village,01-01-1994
114930,/organization/zyraz-technology,/funding-round/c05aab2155e390066d51c6852ff61464,grant,NaN,11-09-2009,5400000.0,Zyraz Technology,http://www.zyraz.com,Biotechnology,closed,MYS,14,MYS - Other,Damansara New Village,01-01-1994
114931,/organization/zyraz-technology,/funding-round/e949f077c943db197f20e43c2eb8d0e6,venture,A,09-10-2009,7991547.0,Zyraz Technology,http://www.zyraz.com,Biotechnology,closed,MYS,14,MYS - Other,Damansara New Village,01-01-1994
114932,/organization/zyrra,/funding-round/2a13fa52848ace2760b224a350a76b40,seed,NaN,15-11-2010,445000.0,Zyrra,http://www.zyrra.com,E-Commerce,operating,USA,MA,Boston,Cambridge,NaN
114933,/organization/zyrra,/funding-round/39baf35e59eb3efc5409cd4c5eaa50e1,seed,NaN,21-10-2010,50000.0,Zyrra,http://www.zyrra.com,E-Commerce,operating,USA,MA,Boston,Cambridge,NaN
114934,/organization/zyrra,/funding-round/7a0fa791c96c9c447ee54662395beab9,venture,NaN,18-10-2012,140500.0,Zyrra,http://www.zyrra.com,E-Commerce,operating,USA,MA,Boston,Cambridge,NaN
114935,/organization/zyrra,/funding-round/cc8cd96a500332d5b4f4bcbddb306099,angel,NaN,15-12-2010,875000.0,Zyrra,http://www.zyrra.com,E-Commerce,operating,USA,MA,Boston,Cambridge,NaN
114936,/organization/zystor,/funding-round/7ea37c0ff4132b084832039a9380d34e,venture,A,16-12-2004,8500000.0,Zystor,http://www.zystor.com,Biotechnology,acquired,USA,WI,Milwaukee,Milwaukee,NaN
114937,/organization/zytoprotec,/funding-round/0c43e717298296d2fb334fb236300f6e,venture,A,29-01-2013,2686600.0,Zytoprotec,http://www.zytoprotec.com,Biotechnology,operating,AUT,3,Vienna,Gerasdorf Bei Wien,01-01-2007
114938,/organization/zzish,/funding-round/34b560f672bebeb339a5efa3b27eae5d,grant,NaN,25-02-2015,400000.0,Zzish,http://www.zzish.com,Analytics|Android|Developer APIs|Education|Gam...,operating,GBR,H9,London,London,28-01-2014
114939,/organization/zzish,/funding-round/4c82e18a8e3eab2647719d0fc27ead5f,angel,NaN,31-10-2014,400000.0,Zzish,http://www.zzish.com,Analytics|Android|Developer APIs|Education|Gam...,operating,GBR,H9,London,London,28-01-2014
114940,/organization/zzish,/funding-round/73721fffc980d228f051e87422aa8732,seed,NaN,24-03-2014,320000.0,Zzish,http://www.zzish.com,Analytics|Android|Developer APIs|Education|Gam...,operating,GBR,H9,London,London,28-01-2014
114941,/organization/zznode-science-and-technology-co...,/funding-round/171693e1e07e0230defd8fddb6de4515,venture,A,01-04-2012,1587301.0,ZZNode Science and Technology,http://www.zznode.com,Enterprise Software,operating,CHN,22,Beijing,Beijing,NaN
114942,/organization/zzzzapp-com,/funding-round/22ef2fafb4d20ac3aa4b86143dbf6c8e,seed,NaN,01-11-2011,7000.0,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,operating,HRV,15,Split,Split,13-05-2012
114943,/organization/zzzzapp-com,/funding-round/6ba41360588bc6e3f77e9b50a0ebfafa,seed,NaN,01-08-2013,33149.0,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,operating,HRV,15,Split,Split,13-05-2012
114944,/organization/zzzzapp-com,/funding-round/8f6d25b8ee4199e586484d817bceda05,convertible_note,NaN,01-03-2014,41313.0,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,operating,HRV,15,Split,Split,13-05-2012
114945,/organization/zzzzapp-com,/funding-round/ff1aa06ed5da186c84f101549035d4ae,seed,NaN,01-05-2013,32842.0,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,operating,HRV,15,Split,Split,13-05-2012
114946,/organization/ãeron,/funding-round/59f4dce44723b794f21ded3daed6e4fe,venture,A,01-08-2014,NaN,ÃERON,http://www.aeron.hu/,NaN,operating,NaN,NaN,NaN,NaN,01-01-2011
114947,/organization/ãasys-2,/funding-round/35f09d0794651719b02bbfd859ba9ff5,seed,NaN,01-01-2015,18192.0,Ãasys,http://www.oasys.io/,Consumer Electronics|Internet of Things|Teleco...,operating,USA,CA,SF Bay Area,San Francisco,01-01-2014
114948,/organization/ä°novatiff-reklam-ve-tanä±tä±m-h...,/funding-round/af942869878d2cd788ef5189b435ebc4,grant,NaN,01-10-2013,14851.0,Ä°novatiff Reklam ve TanÄ±tÄ±m Hizmetleri Tic,http://inovatiff.com,Consumer Goods|E-Commerce|Internet,operating,NaN,NaN,NaN,NaN,NaN

In [52]:
m = master_frame.groupby('funding_round_type').mean()

In [55]:
m

                       raised_amount_usd
funding_round_type
angel                       9.586945e+05
convertible_note            1.453439e+06
debt_financing              1.704353e+07
equity_crowdfunding         5.383682e+05
grant                       4.300576e+06
non_equity_assistance       4.112031e+05
post_ipo_debt               1.687046e+08
post_ipo_equity             8.218249e+07
private_equity              7.330859e+07
product_crowdfunding        1.363131e+06
secondary_market            7.964963e+07
seed                        7.198180e+05
undisclosed                 1.924237e+07
venture                     1.174895e+07

In [101]:
g= master_frame.loc[master_frame.funding_round_type=='venture']

In [102]:
g

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
66368,/organization/-fame,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0
66369,/ORGANIZATION/-QOUNTER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN
66371,/ORGANIZATION/-THE-ONE-OF-THEM-INC-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0
66372,/organization/0-6-com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0
66373,/ORGANIZATION/004-TECHNOLOGIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/1278dd4e6a37fa4b7d7e06c21b3c1830,venture,NaN,24-07-2014,NaN
66376,/organization/0ndine-biomedical-inc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/954b9499724b946ad8c396a57a5f3b72,venture,NaN,21-12-2009,719491.0
66378,/ORGANIZATION/0XDATA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/ae2a174c06517c2394aed45006322a7e,venture,NaN,03-01-2013,1700000.0
66379,/organization/0xdata,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/3bb2ee4a2d89251a10aaa735b1180e44,venture,B,09-11-2015,20000000.0
66380,/organization/0xdata,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/e1cfcbe1bdf4c70277c5f29a3482f24e,venture,A,19-07-2014,8900000.0
66390,/organization/1-mainstream,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/b952cbaf401f310927430c97b68162ea,venture,NaN,17-03-2015,5000000.0
66396,/organization/10-minutes-with,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/0faccbbcc5818dc5326469f13f5a8ac8,venture,A,09-10-2014,4000000.0
66401,/ORGANIZATION/1000LOOKZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/e07f6e580046d00c7aeb33fafb9d90a3,venture,NaN,22-07-2013,NaN
66402,/organization/1000memories,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/502bd0e50c27616995e4bdad24605ef8,venture,A,16-02-2011,2520000.0
66405,/organization/1000museums-com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/13be128d655076a025221d7fddc90d68,venture,NaN,14-10-2009,265940.0
66407,/organization/1000museums-com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/adf2f3272af9f552b87e01f10f0b9234,venture,NaN,01-02-2014,NaN
66408,/organization/1000museums-com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/fd1b3064232ba9b3cfb5653a619e82e8,venture,NaN,05-04-2011,642000.0
66410,/ORGANIZATION/1000MUSEUMS-COM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/6aeb32ab3fc05db2b606d7a2466e8c09,venture,NaN,15-01-2014,2906832.0
66411,/ORGANIZATION/1000MUSEUMS-COM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/89317984885b44f02e4befb9dc2e588c,venture,NaN,01-08-2014,1500000.0
66414,/ORGANIZATION/1001-MENUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/8025123b90c1ab687f9857ffe18bfd3b,venture,A,13-11-2013,1736910.0
66415,/ORGANIZATION/1001-MENUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/b6c28ea4ebe32db7083052cf87e7c368,venture,A,25-10-2013,1800000.0
66416,/organization/1001-menus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/645b4cd895450b8e0268027cd7813047,venture,B,04-11-2015,6602694.0
66418,/organization/1001pharmacies-com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/a21fc4d20200f43e3a25fd9cfc7c1482,venture,A,09-07-2015,8900000.0
66420,/ORGANIZATION/1006-TV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/c4dd206906e8f6834dde0eb9681002ac,venture,A,01-01-2013,NaN
66421,/organization/1006-tv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/b6aeb7401ec6993f92a16cbca153b600,venture,B,31-07-2014,10000000.0
66422,/organization/100du-tv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/46a9d3228f69c036e8076f1362ac58cd,venture,C,13-08-2010,NaN
66423,/ORGANIZATION/100DU-TV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/8797d60368bb0227f0d0ab4c72aef886,venture,A,07-01-2008,3000000.0
66424,/organization/100e-com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/22a86670d1055d7bafce665b27e91871,venture,NaN,01-01-2006,3000000.0
66425,/ORGANIZATION/100E-COM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/a136f7eb873dfb13cec839fef7d7f51e,venture,NaN,01-09-2006,1500000.0
66427,/ORGANIZATION/100HEALTH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/502f558bee350299fd1ae503e5b9a124,venture,A,20-10-2015,3530000.0
66429,/ORGANIZATION/100PLUS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/b5facb0d9dea2f0352b5834892c88c53,venture,NaN,02-11-2011,500000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181259,/organization/zymeworks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/fff65853a50d907bdf362b572076f1d1,venture,C,26-06-2009,3500000.0
181260,/ORGANIZATION/ZYMEWORKS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/917b2ed7b99f219fcbc660c9789482d5,venture,D,22-09-2011,8100000.0
181261,/ORGANIZATION/ZYMEWORKS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/d7b019f508ef724ca3a851a4359a272f,venture,NaN,06-09-2012,11000000.0
181262,/ORGANIZATION/ZYMEWORKS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/fd4f9cd4c2ad9c8980848491cd467f35,venture,NaN,13-01-2015,23988700.0
181263,/ORGANIZATION/ZYMOCHEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/7735e006f2ffa443d9d7e2312173bf93,venture,NaN,16-03-2015,NaN
181268,/organization/zyncd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/3549f5a481f83610044a4226926acf5a,venture,NaN,01-09-2014,144451.0
181270,/organization/zyncro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/35310bcb0945d9d4b5ffa5482e5c87f3,venture,B,03-02-2012,2105600.0
181271,/ORGANIZATION/ZYNCRO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/c8dd9ae33cc5d5a1d972b470a5955373,venture,A,05-04-2011,1699920.0
181272,/organization/zynerba-pharmaceuticals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/8992160f6abc8e21563e54a6e97a8922,venture,NaN,14-10-2014,13000000.0
181273,/ORGANIZATION/ZYNERGY-PROJECTS-SERVICES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/3d7dbd2d92220d93e2b5455f914a0918,venture,NaN,19-08-2015,NaN
181274,/organization/zynga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/1bc4f7b3a778e5abfbd7131f595f5011,venture,B,04-11-2009,15187000.0
181275,/organization/zynga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/66d64809546fe2031d3479161e3c88f9,venture,A,01-01-2008,10000000.0
181276,/organization/zynga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/8411431b5a0389a874e3fae93016c089,venture,B,24-04-2010,15000000.0
181277,/organization/zynga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/cf8299f657f7fd4cf01054ee1934109c,venture,B,14-06-2010,300000000.0
181278,/organization/zynga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/eb198261da812bc8d3bf475ccec44000,venture,A,12-02-2008,5026000.0
181279,/ORGANIZATION/ZYNGA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/5bebd7acdfd44138f81d162f21c532f9,venture,NaN,12-10-2010,6337786.0
181280,/ORGANIZATION/ZYNGA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/72e4fdf2cfb0cdc0750f90e486722068,venture,B,18-07-2008,25000000.0
181281,/ORGANIZATION/ZYNGA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/a6ebc53cf3c0c97d1cdd075f6bbf31fa,venture,C,18-02-2011,490000000.0
181283,/ORGANIZATION/ZYNGENIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/55ec03b6fa2e812a2b4a9da5a4555752,venture,A,09-09-2010,25000000.0
181284,/organization/zynstra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/05f43b37c270f5919578281ce803de8f,venture,B,09-07-2014,8400000.0
181286,/ORGANIZATION/ZYNSTRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/129127802dd48be42d6cd45f65895245,venture,A,12-09-2013,3800000.0
181288,/organization/zyomyx-inc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/4191cb5258d3863b0212d1083881da64,venture,B,30-06-2013,12000000.0
181289,/organization/zyomyx-inc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/b4fce7f8a13267353d57db09099800e8,venture,NaN,11-07-2013,14219999.0
181291,/ORGANIZATION/ZYOMYX-INC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/ea5b21da6cf999ff4d5667431fe318d7,venture,NaN,29-01-2010,555016.0
181299,/ORGANIZATION/ZYRAZ-TECHNOLOGY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/e949f077c943db197f20e43c2eb8d0e6,venture,A,09-10-2009,7991547.0
181301,/organization/zyrra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/7a0fa791c96c9c447ee54662395beab9,venture,NaN,18-10-2012,140500.0
181304,/organization/zystor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/7ea37c0ff4132b084832039a9380d34e,venture,A,16-12-2004,8500000.0
181305,/ORGANIZATION/ZYTOPROTEC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/0c43e717298296d2fb334fb236300f6e,venture,A,29-01-2013,2686600.0
181309,/ORGANIZATION/ZZNODE-SCIENCE-AND-TECHNOLOGY-CO...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/171693e1e07e0230defd8fddb6de4515,venture,A,01-04-2012,1587301.0
181314,/organization/ãeron,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/funding-round/59f4dce44723b794f21ded3daed6e4fe,venture,A,01-08-2014,NaN

In [100]:
g

Empty DataFrame
Columns: [permalink, name, homepage_url, category_list, status, country_code, state_code, region, city, founded_at, funding_round_permalink, funding_round_type, funding_round_code, funded_at, raised_amount_usd]
Index: []

In [99]:
h.head()

Empty DataFrame
Columns: [permalink, name, homepage_url, category_list, status, country_code, state_code, region, city, founded_at, funding_round_permalink, funding_round_type, funding_round_code, funded_at, raised_amount_usd]
Index: []

In [96]:
k=h.sort_values(by=['raised_amount_usd'],ascending=Fal

AttributeError: Cannot access callable attribute 'sort_values' of 'DataFrameGroupBy' objects, try using the 'apply' method

In [89]:
h= h[h['country_code'].notnull()]

In [94]:
h.head()

Empty DataFrame
Columns: [permalink, name, homepage_url, category_list, status, country_code, state_code, region, city, founded_at, funding_round_permalink, funding_round_type, funding_round_code, funded_at, raised_amount_usd]
Index: []

In [24]:
i = companies['category_list']

In [25]:
type(i)

pandas.core.series.Series

In [26]:
companies['category_list']= companies['category_list'].str.split("|", n = 1, expand = True)

In [27]:
companies.head()

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/organization/-fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
1,/organization/-qounter,:Qounter,http://www.qounter.com,Application Platforms,operating,USA,DE,DE - Other,Delaware City,04-09-2014
2,/organization/-the-one-of-them-inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps,operating,NaN,NaN,NaN,NaN,NaN
3,/organization/0-6-com,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
4,/organization/004-technologies,004 Technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign,01-01-2010

In [28]:
mapping = pd.read_csv("mapping.csv",encoding="ISO-8859-1")

In [29]:
mapping.head()

,category_list,Automotive & Sports,Blanks,Cleantech / Semiconductors,Entertainment,Health,Manufacturing,"News, Search and Messaging",Others,"Social, Finance, Analytics, Advertising"
0,NaN,0,1,0,0,0,0,0,0,0
1,3D,0,0,0,0,0,1,0,0,0
2,3D Printing,0,0,0,0,0,1,0,0,0
3,3D Technology,0,0,0,0,0,1,0,0,0
4,Accounting,0,0,0,0,0,0,0,0,1

In [34]:
mapping['sector']=mapping.apply(get_col_name,value==1)

NameError: name 'get_col_name' is not defined

In [37]:
lines = list(mapping)

In [58]:
n= mapping.values.tolist()

In [73]:
c=list(mapping.columns.values)

In [85]:
c[2]

'Blanks'

In [127]:
np.shape(n)[0]

688

In [128]:
s = [None] * np.shape(n)[0]

for i in range(np.shape(n)[0]):
    for j in range(10):
        if(n[i][j] == 1):
            s[i] = c[j]
            print(s[i])

Blanks
Manufacturing
Manufacturing
Manufacturing
Social, Finance, Analytics, Advertising
Health
Social, Finance, Analytics, Advertising
Manufacturing
Automotive & Sports
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Others
Automotive & Sports
Manufacturing
Cleantech / Semiconductors
Others
Others
Others
Health
Others
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Others
Health
Social, Finance, Analytics, Advertising
News, Search and Messaging
News, Search and Messaging
News, Search and Messaging
News, Search and Messaging
News, Search and Messaging
News, Search and Messaging
Cleantech / Semiconductors
Manufacturing
News, Search and Messaging
Entertainment
Social, Finance, Analytics, Advertising
Entertainment
Health
Health
Social, Finance, Analytics, Advertising
Entertainment
Entertainment
Social, Finance, Analytics, Advertising
Automotive & Sports
Automotive & Sports
Automotive & Sports
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Health
Health
Health
Health
Social, Finance, Analytics, Advertising
Manufacturing
Health
Automotive & Sports
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Cleantech / Semiconductors
Cleantech / Semiconductors
Cleantech / Semiconductors
Cleantech / Semiconductors
Cleantech / Semiconductors
Cleantech / Semiconductors
Cleantech / Semiconductors
News, Search and Messaging
Automotive & Sports
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Entertainment
Social, Finance, Analytics, Advertising
News, Search and Messaging
News, Search and Messaging
News, Search and Messaging
News, Search and Messaging
Manufacturing
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Entertainment
News, Search and Messaging
Automotive & Sports
News, Search and Messaging
Health
Cleantech / Semiconductors
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Automotive & Sports
Entertainment
Entertainment
News, Search and Messaging
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
News, Search and Messaging
Cleantech / Semiconductors
Health
News, Search and Messaging
Manufacturing
News, Search and Messaging
Cleantech / Semiconductors
Cleantech / Semiconductors
Cleantech / Semiconductors
Health
News, Search and Messaging
News, Search and Messaging
News, Search and Messaging
News, Search and Messaging
News, Search and Messaging
News, Search and Messaging
Entertainment
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Others
Others
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Entertainment
News, Search and Messaging
Cleantech / Semiconductors
Cleantech / Semiconductors
Manufacturing
Manufacturing
Social, Finance, Analytics, Advertising
News, Search and Messaging
Manufacturing
Manufacturing
Cleantech / Semiconductors
Entertainment
Entertainment
Manufacturing
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Manufacturing
Manufacturing
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Entertainment
Entertainment
Entertainment
Entertainment
Entertainment
Entertainment
Health
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Health
Health
Health
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Entertainment
Entertainment
Entertainment
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
News, Search and Messaging
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Manufacturing
News, Search and Messaging
News, Search and Messaging
Health
Automotive & Sports
Automotive & Sports
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Health
Health
Health
Entertainment
Entertainment
Entertainment
Entertainment
Social, Finance, Analytics, Advertising
News, Search and Messaging
News, Search and Messaging
Social, Finance, Analytics, Advertising
Manufacturing
Cleantech / Semiconductors
Others
Others
Others
Health
Others
Manufacturing
News, Search and Messaging
Automotive & Sports
Entertainment
Others
Others
Cleantech / Semiconductors
Entertainment
Others
Others
Others
Others
Entertainment
Entertainment
Health
Automotive & Sports
Manufacturing
Health
Manufacturing
News, Search and Messaging
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Manufacturing
Others
Social, Finance, Analytics, Advertising
Others
Cleantech / Semiconductors
Cleantech / Semiconductors
Cleantech / Semiconductors
Cleantech / Semiconductors
Cleantech / Semiconductors
Others
Others
Others
Social, Finance, Analytics, Advertising
Others
News, Search and Messaging
Others
Others
Others
Entertainment
Entertainment
Others
Cleantech / Semiconductors
Social, Finance, Analytics, Advertising
Entertainment
Entertainment
Health
Health
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Others
Entertainment
Manufacturing
Manufacturing
Entertainment
Cleantech / Semiconductors
Others
Others
Entertainment
Entertainment
Entertainment
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Health
Others
Others
Others
Others
Manufacturing
Manufacturing
News, Search and Messaging
Social, Finance, Analytics, Advertising
Others
Social, Finance, Analytics, Advertising
Entertainment
Others
Cleantech / Semiconductors
Automotive & Sports
Cleantech / Semiconductors
Manufacturing
Manufacturing
Entertainment
Entertainment
Entertainment
Entertainment
Entertainment
Cleantech / Semiconductors
Others
Others
Health
Others
Others
Others
Others
Social, Finance, Analytics, Advertising
Others
Others
Others
News, Search and Messaging
News, Search and Messaging
Cleantech / Semiconductors
Cleantech / Semiconductors
Manufacturing
Social, Finance, Analytics, Advertising
News, Search and Messaging
Others
Manufacturing
Manufacturing
Manufacturing
Health
Health
Health
Health
Health
Health
Health
Automotive & Sports
Social, Finance, Analytics, Advertising
Others
Others
Others
Cleantech / Semiconductors
Cleantech / Semiconductors
Cleantech / Semiconductors
Others
Others
Others
Others
Others
Health
Entertainment
Others
Others
Others
Others
Others
Others
Others
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Entertainment
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Entertainment
Health
Others
Others
Manufacturing
Automotive & Sports
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Others
Others
Others
Others
Entertainment
Entertainment
News, Search and Messaging
News, Search and Messaging
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
News, Search and Messaging
News, Search and Messaging
Social, Finance, Analytics, Advertising
Others
Others
Others
Others
Others
Entertainment
News, Search and Messaging
Others
Others
Others
Others
Others
Health
Others
Others
Others
Others
Entertainment
Others
Others
Entertainment
Entertainment
Entertainment
Cleantech / Semiconductors
Automotive & Sports
Others
Others
Social, Finance, Analytics, Advertising
Others
Others
Others
News, Search and Messaging
Others
Others
Others
Social, Finance, Analytics, Advertising
Others
Others
Others
Social, Finance, Analytics, Advertising
Manufacturing
News, Search and Messaging
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Others
Others
Others
Cleantech / Semiconductors
Cleantech / Semiconductors
Entertainment
Health
Health
Health
News, Search and Messaging
Health
News, Search and Messaging
Health
Others
News, Search and Messaging
Cleantech / Semiconductors
Cleantech / Semiconductors
News, Search and Messaging
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
News, Search and Messaging
News, Search and Messaging
Entertainment
Health
Manufacturing
Social, Finance, Analytics, Advertising
Others
Social, Finance, Analytics, Advertising
News, Search and Messaging
Manufacturing
Entertainment
Others
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Entertainment
Entertainment
Entertainment
Entertainment
Entertainment
Entertainment
Cleantech / Semiconductors
Cleantech / Semiconductors
Cleantech / Semiconductors
News, Search and Messaging
Others
Others
Health
Manufacturing
Manufacturing
News, Search and Messaging
Others
Others
Others
Health
Others
Others
Others
Others
News, Search and Messaging
Others
Entertainment
Others
News, Search and Messaging
News, Search and Messaging
News, Search and Messaging
News, Search and Messaging
News, Search and Messaging
Entertainment
Others
Others
Manufacturing
Others
Health
Health
Health
Others
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Others
Others
Social, Finance, Analytics, Advertising
News, Search and Messaging
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Others
Social, Finance, Analytics, Advertising
Health
Others
Others
Health
Health
Entertainment
Entertainment
Entertainment
Others
Health
Others
Others
Others
Others
Others
Others
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Others
Social, Finance, Analytics, Advertising
Others
Others
Others
News, Search and Messaging
Others
Others
Others
Others
Others
News, Search and Messaging
Others
Others
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Health
Health
News, Search and Messaging
News, Search and Messaging
Others
Others
Others
Others
Others
News, Search and Messaging
Cleantech / Semiconductors
Others
Cleantech / Semiconductors
Cleantech / Semiconductors
Others
Others
Entertainment
Entertainment
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Entertainment
Others
News, Search and Messaging
Social, Finance, Analytics, Advertising
Others
Others
Social, Finance, Analytics, Advertising
Others
News, Search and Messaging
News, Search and Messaging
Others
Cleantech / Semiconductors
Cleantech / Semiconductors
Health
Health
Others
News, Search and Messaging
Others
Others
Others
Health
Others
Others
Entertainment
Entertainment
Others
Others
Others
Others
Others
Automotive & Sports
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Social, Finance, Analytics, Advertising
Others
Cleantech / Semiconductors
Cleantech / Semiconductors
Health
Health
Health
Automotive & Sports
Automotive & Sports
Others
Others
Social, Finance, Analytics, Advertising
Manufacturing
Others
Others
Others
Others
Others
Others
Others
Others
Others
Others
Entertainment
Others
Entertainment
Health
Entertainment
Entertainment
Others
Others
Others
Others
Automotive & Sports
Entertainment
Entertainment
Others
Others
Automotive & Sports
Others
Others
Others
Others
Others
Social, Finance, Analytics, Advertising
Health
Entertainment
Entertainment
Entertainment
Entertainment
Entertainment
Entertainment
Entertainment
Cleantech / Semiconductors
Others
Cleantech / Semiconductors
Cleantech / Semiconductors
Cleantech / Semiconductors
News, Search and Messaging
News, Search and Messaging
Others
Others
Others
Entertainment
Others
Entertainment
Entertainment
Others
Others

In [125]:
mapping['sector']=s

In [126]:
mapping.head()

,category_list,Automotive & Sports,Blanks,Cleantech / Semiconductors,Entertainment,Health,Manufacturing,"News, Search and Messaging",Others,"Social, Finance, Analytics, Advertising",sector
0,NaN,0,1,0,0,0,0,0,0,0,Blanks
1,3D,0,0,0,0,0,1,0,0,0,Manufacturing
2,3D Printing,0,0,0,0,0,1,0,0,0,Manufacturing
3,3D Technology,0,0,0,0,0,1,0,0,0,Manufacturing
4,Accounting,0,0,0,0,0,0,0,0,1,"Social, Finance, Analytics, Advertising"